title: "Hackathon Merdeka 2.0"
description: "Tujuan dari Hackathon Merdeka 2.0 adalah mengumpulkan solusi untuk pemecahan masalah pengumpulan data yang cepat dan akurat tentang kependudukan."
actioncall: "Setelah sukses menyelenggarakan Hackathon Merdeka yang pertama pada bulan Agustus lalu, Code4Nation kembali mengadakan Hackathon Merdeka pada tanggal 24-25 Oktober serentak di 28 kota di penjuru Indonesia dan para pemenangnya akan dikumpulkan di Jakarta pada momen Hari Sumpah Pemuda 28 Oktober 2015. Ayo bersama-sama kita berkontribusi pada negara untuk menyelesaikan masalah kependudukan!"
email: "hackathon@code4nation.org"
author: "https://code4nation.id"
baseurl: "/hackathon"
url:  "http://khairulanshar.github.io/"
markdown: "kramdown"
timezone: "Asia/Jakarta"
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
